DROP TABLE IF EXISTS Tasks;
CREATE TABLE Tasks
(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR2(50) NOT NULL,
    DESCRIPTION VARCHAR2(1000) NOT NULL,
    START_DATE TIMESTAMP NOT NULL,
    END_DATE TIMESTAMP NOT NULL,
    STATUS VARCHAR2(15) NOT NULL
);

DROP TABLE IF EXISTS TaskCategory;
CREATE TABLE TaskCategory
(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TASK_ID INT NOT NULL,
    CATEGORY_ID INT NOT NULL
);

DROP TABLE IF EXISTS Categories;
CREATE TABLE Categories
(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR2(50) NOT NULL,
    DESCRIPTION VARCHAR2(1000) NOT NULL
);

DROP TABLE IF EXISTS Users;
CREATE TABLE Users
(
   ID INT AUTO_INCREMENT PRIMARY KEY,
   EMAIL VARCHAR2(250) NOT NULL,
   PASSWORD VARCHAR2(20) NOT NULL,
);

DROP TABLE IF EXISTS Authorities;
CREATE TABLE Authorities
(
  ID INT AUTO_INCREMENT PRIMARY KEY,
  USER_ID INT NOT NULL,
  ROLE VARCHAR2(30) NOT NULL
);

INSERT INTO Users(id, email , password) VALUES (1, 'test@gmail.com', 'test');
INSERT INTO Users(id, email , password) VALUES (2, 'admin@gmail.com', 'test');

INSERT INTO Authorities(user_id, role) VALUES (1, 'ROLE_USER');
INSERT INTO Authorities(user_id, role) VALUES (2, 'ROLE_ADMIN');